// flow-typed signature: b51d2ba14f41213235163c7b860da1d7
// flow-typed version: <<STUB>>/bin_v^0.0.0/flow_v0.51.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'bin'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'bin' {
  declare module.exports: any;
}
